spring:
  mail:
    host: smtp.163.com
    password: JNOLNVJCPDAZAPQG
    username: 18850198317@163.com
    default-encoding: UTF-8

#redis
  redis:
    database: 0         # Redis数据库索引（默认为0）
    host: 8.129.216.97  #ip
    port: 6379        #端口
    password: admin   #密码
    jedis:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 2  # 连接池中的最小空闲连接


mail:
  address: 18850198317@163.com

dubbo:
  application:
    name: xyy-dubbo-mail
  registry:
    protocol: zookeeper
    address: 8.129.216.97:2181
  protocol:
    port: 28801

