
dubbo:
  application:
    name: xyy-dubbo-boot
  registry:
    protocol: zookeeper
    address: 192.168.238.130:2181
  protocol:
    port: 28801

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.238.130:22122